packages:
  # Events
  - 'customEvents/typescript'
  - 'customEvents/react'

  # Changelogs
  - 'changelogs/typescript'
  - 'changelogs/react'

  # Feature Flags
  - 'flags/typescript'
  - 'flags/react'

  # CLI Tools
  - 'ionic'
