include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - unawaited_futures








